[package]
name = "iching"
version = "0.1.0"
authors = ["Logan Saether <x@logansaether.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"              # Random number generators and other randomness functionality.
